antora.yml

Attribute page-origin-private was added so edit this page is visible.

Add page-origin-private attribute to antora.yml

---

antora.yml

Attribute page-origin-private was added so edit this page is visible.

Add page-origin-private attribute to antora.yml (#3)

---

modules/ROOT/pages/notifications/all-notifications.adoc

Update to match the changes in Neo4j 5.8: https://github.com/neo-technology/neo4j/pull/20323

Update notification detail for deprecated function and procedures.

---

README.adoc

Аdd the guidelines for writing notifications to the readme (#55)

---

antora.yml

Update version to 5.11 (#67)

---

modules/ROOT/pages/changelogs.adoc
modules/ROOT/pages/notifications/all-notifications.adoc
modules/ROOT/pages/notifications/index.adoc

https://trello.com/c/fQuZB6YA/114-update-to-notification-topology-category-an-repeated-enable-cordon

Adding Topology notification category and ServerAlreadyEnabled

---

modules/ROOT/pages/notifications/all-notifications.adoc

Improve exhaustive shortest path section (#74)

---

README.adoc

Update readme to include guidelines for writing/updating errors

---

antora.yml
modules/ROOT/pages/changelogs.adoc
modules/ROOT/pages/notifications/all-notifications.adoc
modules/ROOT/pages/notifications/index.adoc

Cherry-pick 5.13 PRs

---

antora.yml
modules/ROOT/pages/changelogs.adoc
modules/ROOT/pages/notifications/all-notifications.adoc

Cherry-picked from #89 and #75

Cherry-picks all 5.14 features

---

modules/ROOT/pages/notifications/all-notifications.adoc

The notification will never be issued any more.

Remove side-effect visibility notificatoion

---

README.adoc
modules/ROOT/pages/changelogs.adoc
modules/ROOT/pages/notifications/all-notifications.adoc
modules/ROOT/pages/notifications/index.adoc

Added in https://github.com/neo-technology/neo4j/pull/23899 (merged) and defined in CIP-137.

Add `IndexOrConstraintAlreadyExists` and `IndexOrConstraintDoesNotExist` notifications and new `SCHEMA` notification category

---

README.adoc

Add an example of a parameter within backticks (#122)

---

modules/ROOT/pages/notifications/index.adoc

Documentation about 01N42, 02N42, 03N42. Also tried to remove some duplication by only referring to one single place so the content does not diverge.

Improve docs about compatibility codes

---

modules/ROOT/pages/notifications/index.adoc

Documentation about 01N42, 02N42, 03N42. Also tried to remove some duplication by only referring to one single place so the content does not diverge.
---------

Improve docs about compatibility codes (#172)

---

modules/ROOT/pages/notifications/all-notifications.adoc

[Trello card](https://trello.com/c/L4hfM5CH/529-the-status-notification-code-example-shows-query-with-error)

Fix the example of shortest path with an unbounded pattern

---

modules/ROOT/pages/notifications/all-notifications.adoc

Deprecation message related to
- https://github.com/neo-technology/neo4j/pull/27564
- https://github.com/neo4j/docs-cypher/pull/1084
- cf. [CIP-190](https://docs.google.com/document/d/1AONjI-SpSEla-bHPJ6ghXBfF9alN5mGiOHOTEyfBtRc/edit)

cip-190 deprecations

---

modules/ROOT/pages/changelogs.adoc

Add Neo.ClientNotification.Statement.RuntimeExperimental to the changelog

---

package.json
publish.yml

Update branches to publish

---

modules/ROOT/pages/errors/gql-errors/51N27.adoc
modules/ROOT/pages/errors/gql-errors/index.adoc

Replace 51N27 parameter name item with component

---

modules/ROOT/pages/errors/gql-errors/22N14.adoc
modules/ROOT/pages/errors/gql-errors/index.adoc

To align with changes in https://github.com/neo-technology/neo4j/pull/29493

Change parameters of 22N14

---

modules/ROOT/pages/changelogs.adoc
modules/ROOT/pages/errors/all-errors.adoc
modules/ROOT/pages/notifications/all-notifications.adoc

Update changelog (#263)

---

modules/ROOT/content-nav.adoc
modules/ROOT/pages/errors/gql-errors/42I53.adoc

New error used for parsing the vector value constructor function

New Error - Vector coordinate type

---

modules/ROOT/pages/errors/gql-errors/2DN01.adoc
modules/ROOT/pages/errors/gql-errors/index.adoc

Adapting to https://github.com/neo-technology/neo4j/pull/30353

Update message of 2DN01

---

modules/ROOT/content-nav.adoc

Error missing in the content-nav (#294)

---

modules/ROOT/pages/errors/gql-errors/52N28.adoc

Fix a wrong title for 52N28 (#296)

---

scripts/README.adoc

Update the scripts readme (#310)

---

modules/ROOT/content-nav.adoc
modules/ROOT/pages/errors/gql-errors/52N40.adoc
modules/ROOT/pages/errors/gql-errors/52N41.adoc
modules/ROOT/pages/errors/gql-errors/index.adoc

Add docs for new cluster codes
---------

Add 52N40 and 52N41 (#321)

---

modules/ROOT/content-nav.adoc
modules/ROOT/pages/errors/gql-errors/42I62.adoc
modules/ROOT/pages/errors/gql-errors/index.adoc

Added a new error: https://github.com/neo-technology/neo4j/pull/31206

New Error - Distance metric

---

modules/ROOT/content-nav.adoc
modules/ROOT/pages/errors/gql-errors/22NBD.adoc
modules/ROOT/pages/errors/gql-errors/index.adoc

Introduced in: https://github.com/neo-technology/neo4j/pull/31819
---------

Introduce 22NBD - Unsupported Struct (#371)
