- modules/ROOT/pages/notifications/all-notifications.adoc
Based on this PR: https://github.com/neo-technology/neo4j/pull/18935/files
> Add deprecation warning for using differently ordered return items in UNIONs

- modules/ROOT/pages/notifications/all-notifications.adoc
- Removing deprecation examples for "repeated variable length relationship references" since they are being "undeprecated".
- Adding example `Binding a variable-length relationship variable more than once` to demonstrate a new notification.
Build on top of #35.
> Add example for new notification "Binding a variable-length relationship variable more than once"

- modules/ROOT/pages/notifications/all-notifications.adoc
The id() function has been deprecated since 5.0 but only in the docs. It will now be added in the code as well, hence the new notification.
> Deprecate id() function

- modules/ROOT/pages/changelogs.adoc
- modules/ROOT/pages/notifications/all-notifications.adoc
- modules/ROOT/pages/notifications/index.adoc
https://trello.com/c/1ymz1Qiq/975-create-a-notification-when-doing-allocations-while-some-servers-are-cordoned
This PR proposes the introduction of the `CordonedServersExistedDuringAllocation` notification. This will be returned whenever a command that triggers a database allocation decision is executed. This includes `CREATE DATABASE`, `ALTER DATABASE`, `DEALLOCATE DATABASES FROM SERVER`, `ALTER SERVER`. But not `REALLOCATE DATABASES` as this command has the requirement for no cordoned servers and errors if there is such a server. 
This is useful to remind the person managing the cluster that some servers are cordoned and this impacts the allocation decision (databases can't be allocated to cordoned servers). So this should help the user not get confused by the allocation decisions made. …
> Add `CordonedServersExistedDuringAllocation` notification

- modules/ROOT/pages/changelogs.adoc
- modules/ROOT/pages/notifications/all-notifications.adoc
https://trello.com/c/1ymz1Qiq/975-create-a-notification-when-doing-allocations-while-some-servers-are-cordoned
This PR proposes the introduction of the
`CordonedServersExistedDuringAllocation` notification. This will be returned whenever a command that triggers a database allocation decision is executed. This includes `CREATE DATABASE`, `ALTER DATABASE`, `DEALLOCATE DATABASES FROM SERVER`, `ALTER SERVER`. But not `REALLOCATE DATABASES` as this command has the requirement for no cordoned servers and errors if there is such a server.
This is useful to remind the person managing the cluster that some servers are cordoned and this impacts the allocation decision (databases can't be allocated to cordoned servers). So this should help the user not get confused by the allocation decisions made. …
> Add `CordonedServersExistedDuringAllocation` notification (#86)

- modules/ROOT/pages/changelogs.adoc
- modules/ROOT/pages/notifications/all-notifications.adoc
https://trello.com/c/U9hshewv/1069-alter-database-notification-when-requested-topology-matches-current-topology
This PR proposes the introduction of the `RequestedTopologyMatchedCurrentTopology` notification. This will be returned when an `ALTER DATABASE` command matches the current topology so no allocations are removed/added, e.g., foo has 2 primaries and 1 secondary then I issue an `ALTER DATABASE foo 2 PRIMARIES 1 SECONDARY`.
> Add `RequestedTopologyMatchedCurrentTopology` notification

- modules/ROOT/pages/changelogs.adoc
- modules/ROOT/pages/notifications/all-notifications.adoc
Notification from [OPTIONAL CALL PR](https://github.com/neo-technology/neo4j/pull/26755).
> Added superfluous optional notification

- modules/ROOT/pages/changelogs.adoc
- modules/ROOT/pages/notifications/all-notifications.adoc
Notifications introduced in https://github.com/neo-technology/neo4j/pull/25227 (merged, but behind feature flag). Feature flag removed in https://github.com/neo-technology/neo4j/pull/26923.
> Add notifications for linked users

- modules/ROOT/pages/notifications/all-notifications.adoc
I think we are not using backticks in a consistent way in the code. So, maybe we should reconsider their usage and leave them just for the docs.
> Notification param format

- modules/ROOT/pages/notifications/all-notifications.adoc
> Notification param format (#192)

- modules/ROOT/pages/errors/gql-errors.adoc
Some of them are not marked as implemented in the spreadsheet, but I can see them in the code,
> Add codes starting with 42

- modules/ROOT/pages/errors/gql-errors.adoc
It was decided to remove "on of" from these messages as it sounds weird when there is only one element in the list.
> Update messages for 22N04 and 22N27

- modules/ROOT/pages/errors/gql-errors.adoc
Code update: https://github.com/neo-technology/neo4j/pull/27993/files#diff-384932958624a4a10f07c7751fd5d9840d7a721fcc8e01d0b7e93aa1711d87c7R1768
> Update message for GQL code 22N82

- modules/ROOT/pages/errors/gql-errors.adoc
- modules/ROOT/pages/errors/index.adoc
Will un-draft this after changes to 22N38 are merged (Edit: Changes are merged)
> remove 22G12 and remake 22N38

- modules/ROOT/pages/notifications/all-notifications.adoc
> Clarify situation around the UNION reordering deprecation

- modules/ROOT/pages/changelogs.adoc
- modules/ROOT/pages/notifications/all-notifications.adoc
- modules/ROOT/pages/notifications/index.adoc
Depends on https://github.com/neo-technology/neo4j/pull/28163
> Add notifications for WAIT commands

- modules/ROOT/pages/changelogs.adoc
The information about `neo.ClientNotification.Statement.ParameterNotProvided`, `neo.ClientError.Statement.UnsupportedOperationError`, and `neo.TransientError.Transaction.TransientTransactionFailure` was taken from the U&M guide. See the page on changes to Java API (source code).
> Update the changelog for 5.x

- modules/ROOT/pages/changelogs.adoc
The information about
`neo.ClientNotification.Statement.ParameterNotProvided`, `neo.ClientError.Statement.UnsupportedOperationError`, and `neo.TransientError.Transaction.TransientTransactionFailure` was taken from the U&M guide. See the page on changes to Java API (source code).
> Update the changelog for 5.x (#235)

- package.json
- publish.yml
It is no longer necessary to include the sitemap configuration in the playbook.
This PR also updates some package versions.
> Automatic sitemap generation

- modules/ROOT/content-nav.adoc
This error's link (https://neo4j.com/docs/status-codes/current/errors/gql-errors/#_42n26) is not working because it's not listed in the content-nav file due to a typo.
> Typo causing broken link

- modules/ROOT/content-nav.adoc
- modules/ROOT/pages/errors/gql-errors/50N23.adoc
- modules/ROOT/pages/errors/gql-errors/index.adoc
I hope I did this right - here is the accompanying implementation https://github.com/neo-technology/neo4j/pull/29934
> Add 50N23 for failed Call In Transactions retry

- modules/ROOT/pages/errors/gql-errors/50N21.adoc
- modules/ROOT/pages/errors/gql-errors/52N36.adoc
- modules/ROOT/pages/notifications/all-notifications.adoc
- modules/ROOT/partials/glossary.adoc
> Add examples to the glossary descriptions (#275)

- modules/ROOT/pages/notifications/all-notifications.adoc
> id() changed to a feature deprecated with replacement and move unsupported.dbms.shutdown example to features deprecated without a replacement

- modules/ROOT/pages/notifications/all-notifications.adoc
As this change will not be visible to the user when they get the error, I opted for not including it in changelog/mark as changed in 2025.04. Let me know if you think otherwise.
> Change parameter serverName to server

- modules/ROOT/content-nav.adoc
Causing broken link.
It's also being addressed in the main branch using this PR https://github.com/neo4j/docs-status-codes/pull/293, so no need to cherry-pick it.
> Error missing in the content-nav

- modules/ROOT/pages/errors/gql-errors/42N11.adoc
- modules/ROOT/pages/errors/gql-errors/index.adoc
- modules/ROOT/partials/glossary.adoc
To reflect change made in https://github.com/neo-technology/neo4j/pull/30521
> Change parameter of 42N11 to a list.

- modules/ROOT/pages/errors/gql-errors/22NA5.adoc
- modules/ROOT/pages/errors/gql-errors/42I33.adoc
- modules/ROOT/pages/errors/gql-errors/42I42.adoc
- modules/ROOT/pages/errors/gql-errors/42I50.adoc
- modules/ROOT/pages/errors/gql-errors/42N18.adoc
- modules/ROOT/pages/errors/gql-errors/42N44.adoc
- modules/ROOT/pages/errors/gql-errors/42N73.adoc
- modules/ROOT/pages/errors/gql-errors/50N10.adoc
- modules/ROOT/pages/errors/gql-errors/50N15.adoc
- modules/ROOT/pages/errors/gql-errors/51N61.adoc
- modules/ROOT/pages/errors/gql-errors/51N62.adoc
- modules/ROOT/pages/errors/gql-errors/53N35.adoc
- modules/ROOT/pages/errors/gql-errors/53N37.adoc
- modules/ROOT/pages/errors/gql-errors/53U00.adoc
- modules/ROOT/pages/errors/gql-errors/index.adoc
- modules/ROOT/templates/gql-index-template.adoc
- scripts/README.adoc
- scripts/generate-gql-error-index-from-template.py
- scripts/update-gql-error-index.py
- scripts/validate-error-auto-index.py
- scripts/validate-error-index.py
> Generate gql-errors index.adoc file (#302)

- modules/ROOT/content-nav.adoc
- modules/ROOT/pages/errors/gql-errors/22N90.adoc
- modules/ROOT/pages/errors/gql-errors/22NB9.adoc
- modules/ROOT/pages/errors/gql-errors/index.adoc
- modules/ROOT/partials/glossary.adoc
Introduced in https://github.com/neo-technology/neo4j/pull/30884
> Document new GQLSTATUS 22NB9

- modules/ROOT/pages/errors/all-errors.adoc
A similar one https://github.com/neo4j/docs-operations/pull/2330
> Add a note that error messages are deprecated

- modules/ROOT/content-nav.adoc
- modules/ROOT/pages/errors/gql-errors/52N40.adoc
- modules/ROOT/pages/errors/gql-errors/52N41.adoc
- modules/ROOT/pages/errors/gql-errors/index.adoc
Add docs for new cluster codes
> Add 52N40 and 52N41

- modules/ROOT/pages/notifications/all-notifications.adoc
This is a partial backport of https://github.com/neo4j/docs-status-codes/pull/340 to cover the changes applicable to 5.26.
> Removal of old graph reference deprecation.

- modules/ROOT/content-nav.adoc
- modules/ROOT/pages/errors/gql-errors/42I64.adoc
- modules/ROOT/pages/errors/gql-errors/index.adoc
Adds error for [PR](https://github.com/neo-technology/neo4j/pull/31952) - unsupported aggregation in NEXT.
> Added 42I64 - unsupported aggregation

- modules/ROOT/pages/errors/gql-errors/22N69.adoc
- modules/ROOT/pages/errors/gql-errors/22N71.adoc
- modules/ROOT/pages/errors/gql-errors/index.adoc
Updated in https://github.com/neo-technology/neo4j/pull/31435 (merged the day after cutoff for 2025.06)
> Update 22N69 and 22N71 to have more consistent wording when compared to the corresponding constraint errors

- modules/ROOT/pages/errors/gql-errors/42I64.adoc
- modules/ROOT/pages/errors/gql-errors/index.adoc
Rename 42I64 to unsupported operation
[Neo4j PR](https://github.com/neo-technology/neo4j/pull/32037)
> 42I64 - Unsupported operation

- modules/ROOT/content-nav.adoc
- modules/ROOT/pages/errors/gql-errors/22NBD.adoc
- modules/ROOT/pages/errors/gql-errors/index.adoc
Introduced in: https://github.com/neo-technology/neo4j/pull/31819
> Introduce 22NBD - Unsupported Struct

- modules/ROOT/content-nav.adoc
- modules/ROOT/pages/errors/gql-errors/42I65.adoc
- modules/ROOT/pages/errors/gql-errors/42I66.adoc
- modules/ROOT/pages/errors/gql-errors/index.adoc
Error codes introduced in [PR Formatting temporals](https://github.com/neo-technology/neo4j/pull/32184)
> Error codes: 42I65 and 42I66

- modules/ROOT/content-nav.adoc
- modules/ROOT/pages/errors/gql-errors/42I09.adoc
- modules/ROOT/pages/errors/gql-errors/42I67.adoc
- modules/ROOT/pages/errors/gql-errors/index.adoc
Adds error 42I67 introduced in [PR](https://github.com/pulls)
> Added error code 42I67 unsupported language feature

- modules/ROOT/pages/notifications/all-notifications.adoc
Since text-2.0 index provider is legacy now.  
Also, fix the message:)
> Update deprecation message for legacy text index providers.
